name: app_inventario
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI e stile
  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0
  fl_chart: ^0.66.2
  percent_indicator: ^4.2.2
  table_calendar: ^3.0.0
  syncfusion_flutter_charts: ^28.2.11
  radar_chart: ^2.1.0

  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  excel: ^2.1.0
  # Navigazione e stato
  provider: ^6.1.2

  # Database locale
  isar: ^3.1.0
  isar_flutter_libs: any

  # Gestione file e PDF
  file_picker: ^6.1.1
  path_provider: ^2.0.15
  pdf: ^3.10.4
  printing: ^5.11.0
  # Audio/Video
  flutter_sound: ^9.2.13
  video_player: ^2.7.0
  speech_to_text: ^6.3.0
  # Permessi e notifiche
  permission_handler: ^10.0.0
  flutter_local_notifications: ^16.2.0

  timezone: ^0.9.1
  csv: ^5.0.0
  url_launcher: ^6.1.8
  jitsi_meet: ^4.0.0
  collection: ^1.19.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
  # Aggiungi qui le tue immagini o PDF se vuoi:
  # assets:
  #   - assets/pdf/
  #   - assets/images/
